metastore:
    glue:
        catalog_id: ""
    hive:
        db_location_uri: file:/user/hive/warehouse/
        uri: ""
server:
    retries:
        enabled: true
        max_attempts: 4
        max_wait_interval: 30s
        min_wait_interval: 200ms
